name: Build

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_ENVIRONMENT: github
  ASPNETCORE_ENVIRONMENT: github
  BUILD_PATH: "${{github.workspace}}/artifacts"
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

on:
  push:
    branches:
      - master
      - develop
    tags:
      - "v*"
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore --configuration Release

      - name: Run Test
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" --settings coverlet.runsettings

      - name: Report Coverage
        if: success()
        uses: coverallsapp/github-action@v2
        with:
          file: "${{github.workspace}}/test/*/TestResults/*/coverage.info"
          format: lcov

      - name: Create Packages
        if: success() && github.event_name != 'pull_request'
        run: dotnet pack --configuration Release --no-build --output "${{env.BUILD_PATH}}/packages"

      - name: Publish Samples
        if: success() && github.event_name != 'pull_request'
        run: dotnet publish ./samples/Sample.ClientSide/Sample.ClientSide.csproj --configuration Release --output "${{env.BUILD_PATH}}/sample"

      - name: Upload Packages
        if: success() && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v5
        with:
          name: packages
          path: "${{env.BUILD_PATH}}/packages"

      - name: Upload Sample Web Site
        if: success() && github.event_name != 'pull_request' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
        uses: actions/upload-pages-artifact@v4
        with:
          name: github-pages
          path: "${{env.BUILD_PATH}}/sample/wwwroot"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.event_name != 'pull_request' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v6
        with:
          name: packages

      - name: Publish Packages GitHub
        run: |
          for package in $(find -name "*.nupkg"); do
            echo "${0##*/}": Pushing $package...
            dotnet nuget push $package --source https://nuget.pkg.github.com/loresoft/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
          done

      - name: Publish Packages feedz
        run: |
          for package in $(find -name "*.nupkg"); do
            echo "${0##*/}": Pushing $package...
            dotnet nuget push $package --source https://f.feedz.io/loresoft/open/nuget/index.json --api-key ${{ secrets.FEEDDZ_KEY }} --skip-duplicate
          done

      - name: Publish Packages Nuget
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          for package in $(find -name "*.nupkg"); do
            echo "${0##*/}": Pushing $package...
            dotnet nuget push $package --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }} --skip-duplicate
          done

  pages:
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v')

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy Sample
        id: deployment
        uses: actions/deploy-pages@v4

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
